### ISSUE TITLE
Legacy Type with turning keys

### ISSUE THREAD

**Issue by Nicolas-GE** [Drahsid/HybridCamera#3]
as title implies, i would love for this mod to be able to have Legacy Type movement but still allow for spinning around one place with the turn left&right keys (like for doing an emote while spinning)

**Comment by Drahsid** [comment]
If you have the turn keys bound, then you can turn in place while idle as long as you don't have it bound to one of the legacy-mode keys. The behavior which makes you move (instead of turn) is a feature of legacy mode, and changing that would just make it a busted version of standard mode. If you want to turn in place, by the design of the game's movement options, you need to be in standard move (movement would be strange.) You can accomplish this by either unbinding A and D from the legacy key list, or by binding the turn keys elsewhere (like Q or E, for example).

**Comment by krazyito65** [comment]
I guess i dont understand quite what you mean here.

For me, I much prefer standard movement for everything EXCEPT when i have to cast a instant spell and it jerks my camera around..

I use all 6 of my buttons (QWE/ASD) for movement, and very often use a strafe + turn key at the same time.


I've found if i set W as a 'legacy' key, this works pretty well for my needs with this plugin, but if I set Q or E (or A or D) i lose the ability to move while turning.

Is there a way I could say, add QWE as legacy buttons, BUT if Q + A/D or E +A/D forces it back to standard?  I know its kind of a niche take but that would make this plugin more useful for me.

**Comment by krazyito65** [comment]
I also tried to use legacy when only pushing dps buttons, but that did not work very well

**Comment by Drahsid** [comment]
I'll go ahead and describe what happens in each mode to try and help you figure out how you want to set this up.

So firstly, there are two types of horizontal input, strafe, and turn. Under the movement keybinds, strafe is labeled as "Strafe [Left/Right]" commands. Similarly, turn is labeled "Move [Left/Right] / Turn [Left/Right]"

These behave slightly differently based on your current movement mode. Note that the general idea of Standard mode is to move in a direction relative to the player character. Conversely, the general idea of Legacy is to move in a direction relative to the camera. 

Quickly going over the difference between strafe and turn:

## Standard Movement Mode

### Turn
In **standard movement** mode, turn slowly rotates the player character. It does this by adding some static value to the yaw rotation while the key is being held. This means you can run in circles by holding forward and one of the turn keys, or simply turn in place.
**Something important to consider with _standard movement turning_** is the "Standard Type Camera Auto-adjustment" option. See below where I describe Camera Auto-adjustment for move info.

### Strafe
In **standard movement** mode, strafe moves the player-character along their own right/left axis. When additionally moving on the forward/backward axis, the direction you move is blended, with a minor preference towards the forward/backward axis.

## Legacy Movement Mode

### Turn
In **legacy movement** mode, turn moves the player-character along the left/right axis of the camera. When additionally moving on the forward/backward axis, the direction you move is blended equally with the forward/backward axis. In **legacy movement** mode, turn also orients the player-character in the direction they move. This means that when only moving horizontally, you will turn left/right as you move in that direction, and when moving diagonally, the player-character points towards that diagonal direction.

### Strafe
In **legacy movement** mode, strafe moves the player-character along the left/right axis of the camera. When additionally moving on the forward/backward axis, the direction you move is blended equally with the forward/backward axis. In **legacy movement** mode, strafe also orients the player-character in the direction of the camera. Because of this, by default the player-character will backpedal when the game does not think that they are turning (this is something you can fix with this mod.)

## Important things

### Legacy Movement Mode -> Disable Camera Pivot
**Disable Camera Pivot** turns off a feature which makes the player-character move slightly inward when moving horizontally, which results in movement being more like a wide circle instead of straight. Other games call this things like "Auto camera," and "Camera Follow." This movement technique was originally implemented in old games to deal with lack precise camera control, and to help players who were new to 3D games rotate the camera with only movement input. 
I _**highly suggest**_ toggling this option, since it's default state (being off) is unintuitive at best, and disrespectful to the player at worst.

### Camera Auto-adjustment
**Camera Auto-adjustment** is a setting which likely messes with a lot of people, and they don't even know about it. It basically makes the camera align with the player-character. The **"Always"** option means that the camera will constantly align with the player-character. The **"Only When Moving"** option means that the camera will align with the player-character while it is in motion. The **"Never"** option disables Camera Auto-adjustment.
I personally think in most cases, for most people, that this setting should be set to **"Never"**, as the other options seem disruptive to me, but this is something that users should test on their own.

## Settings that I suggest starting with

Firstly, I suggest adjusting the actual movement options so they don't hinder with your intent. For this, I suggest the following settings:

- Character Configuration -> Control Settings -> General -> Legacy Type -> Disable Camera pivot: **Toggle on**
- Character Configuration -> Control Settings -> General -> Standard Type Camera Auto-adjustment: **Set to Never**
- Character Configuration -> Control Settings -> General -> Standard Type Camera Auto-adjustment  -> Enable Y-axis auto-adjustment: **Toggle off**
- Character Configuration -> Control Settings -> General -> 1st Person Camera Auto-adjustment: **Set to Never**
- Character Configuration -> Control Settings -> General -> 1st Person Camera Auto-adjustment -> Enable Y-axis auto-adjustment: **Toggle off**
- Character Configuration -> Control Settings -> Target -> Automatically face target when using action: **Toggle on** _(Unless you are playing the game entirely in first person, in which case I suggest toggling this off)_
- System -> Keybind ->Movement: **Bind Strafe as your default horizontal movement** _(For most people, this would be A and D)_

Secondly, within Hybrid Camera's configuration, start with the following:
- Have your movement keys (WASD for most people) on the "Add and remove the keys for legacy mode below" list.
- General Settings -> Use  turning on backpedal: **Toggle on** (this makes backwalking full speed)



Hope this helps!

**Comment by krazyito65** [comment]
I appreciate you taking the time to fully detail everything out.  When reading through your settings, i was pretty sure it wasn't going to really achieve what I wanted, and it didn't, but I went ahead and implemented the whole thing anyway to be sure.  


> Camera Auto-adjustment
This option, I do want to be 'only while moving'.  Its just something I've been use to playing with for a long time and I actively use it while strafe-turning.  It may not be 'ideal' but 10 years of MMO movement I've just gotten use to doing this.  I do also move my camera with my right click button, but thats usually when I need much faster/ larger movements. 

>System -> Keybind ->Movement: Bind Strafe as your default horizontal movement (For most people, this would be A and D)

This portion i was the most confused about.  Do you just mean setting strafe to A/D and unbinding turn?
![image](https://github.com/Drahsid/HybridCamera/assets/479738/7a318654-e36a-4008-8db3-520e0012a3c9)

If this is the case, then how am I suppose to turn, outside of right clicking?  I didn't mention it in the first post, but as I said here, I do a mix of both.  Not being able to press Q + D to 'strafe-turn' just feels unnatural to me. 

> General Settings -> Use turning on backpedal: Toggle on (this makes backwalking full speed)
I may not understand the point of this as well, because to me, this just uses 'legacy camera' only when you're using a movement key, which i guess is the point of the plugin, but at least from what I've seen while using it, this feel/does nothing different from using legacy mode all the time?  The only time its in standard mode is when im standing still, which im not sure what the point is.  I could just be totally misunderstanding though.
---
Another Option I've thought of is using 'space' as a 'hold to toggle' where I just hold space or some other modifier to force legacy mode, which would prevent me from changing direction while moving like i wanted, but i found it somewhat awkward to hold spacebar for that, but maybe its just something i should get use to.  

I was hoping I could just apply it to a movement key, but I find it quite annoying not having my character do any movement when holding strafe + turn keys, they just stand still :(

Another option is simply only apply 'legacy mode' to forward and backwards, which will probably work for almost every case, except when I'm strafing.  I may need to actually use it in more specific contexts to see how often i would still be 'jerked' around, but this is likely my best case scenario currently.  The only issue with this is, when idling (or just running around in circles in town) I do find myself sometimes pressing Q+W+D, which does a turning strafe kind of in between W+D or Q+D, and with this config, Q+W+D just moves my character forward, since legacy mode basically removes the strafe-turning functionality.

---
In the end, I think to really get what I personally want, is to keep standard mode mostly default, and simply hold right click and 'shake' the camera as I move to quickly reset my facing when i cast a spell, though this is mostly only useful on fights such as P10S where you are trying to cast a spell while running across the small webbed bridge...

Its probable this plugin does not fit my use-case, and thats ok! I was just hoping there might be a way to do it, which from the testing ive done with the options I've seen and your suggestions, I don't think there is a way.

Please let me know if i've misunderstood anything or need better clarification.

**Comment by Drahsid** [comment]
> i was pretty sure it wasn't going to really achieve what I wanted, and it didn't, but I went ahead and implemented the whole thing anyway to be sure.
Sorry, I should have been more clear about what I wrote. I meant to make it clear how the settings effect movement in game, and suggest a general starting point for anyone who is confused (which seems common enough to warrant a detailed explanation.) Your specific wishes for controls is the sort-of situation I hadn't really considered, so I'm not immediately sure about what the best option for it would be.

> This portion i was the most confused about. Do you just mean setting strafe to A/D and unbinding turn?
Unbinding turn wasn't necessary here (You could put it on Q/E for example,) the intent of using strafe as the main movement method is to make it strictly horizontal movement consistent. This mod has settings called "use turn on front/backpedal", which conditionally change strafing to turning on diagonals.
This doesn't really fit what you want in it's entirety, and was just part of my starting point example.

> I may not understand the point of this as well, because to me, this just uses 'legacy camera' only when you're using a movement key, which i guess is the point of the plugin, but at least from what I've seen while using it, this feel/does nothing different from using legacy mode all the time?
Using standard mode while not moving, and legacy mode while moving has a couple traits that are otherwise impossible. The main one is that it makes it so that your player-character will always be oriented with the camera. There are some other minor things like making the rules for turning more consistent. It is mostly the same as just using legacy though.

> Another Option I've thought of is using 'space' as a 'hold to toggle'
Having an button to quick toggle between standard and legacy could probably be a bit less clunky. Though in that regard, it probably wouldn't be much more difficult to add the option to add key combinations so you could just make it work with the conditions that you want.

> edit: As a final note as I've been trying to do more testing, is there an option in the 'Add and remove the keys for legacy mode below' portion to work with my right click? I think it would also help if my right click toggled legacy mode instead.
Mouse input had a lot of issues due to the UI. I tried implementing it a while ago. It's not there because the stuff I had didn't   work very well.

**Comment by krazyito65** [comment]
Alright, I appreciate you taking the time to respond. I think this just doesn't do what i want for my nice case, which is fine. :) Thank you again for the explanations.
