### ISSUE TITLE
Legacy but Standad Camera Rotation

### ISSUE THREAD

**Issue by Sloth-Girl** [Drahsid/HybridCamera#4]
Hello!
I played with the Standard movement as a Tank, but after a few fights in Savage's current tier I switched to Legacy but I miss the camera rotation in Standard mode for no-look mechanics, where I could turn my character just by rotating the camera.
Would there be a way for the plugin to not block my movement in Standard mode and allow me to use the camera rotation option as a standalone?

**Comment by Drahsid** [comment]
I made this plugin pretty much for this specific purpose. You can achieve it with the following settings:

In hybrid camera config:
![image](https://github.com/Drahsid/HybridCamera/assets/19179468/2971267a-9650-41af-b194-9c8857c9c2f4)

In **Character Configuration**->**Control Settings**
Under **Legacy Type (Camera-Based)**:
Enable **Disable camera pivot**
Enable **Maintain camera distance**
Enable **Activate standard type auto-fly/auto-dive**

Under **Standard Type Camera Auto-adjustment**:
Set the drop down to **Never**
Disable **Enable Y-axis auto-adjustment**

Finally, consider using strafe on A and D, instead of the default keybind which uses turning movement. This can be changed in **System**->**Keybind**

Let me know if you have any issues.

**Comment by Sloth-Girl** [comment]
I had almost made it work, but the camera was shaking slightly and bothering me, but with the settings you gave me for the camera's automatic adjustment, it was perfect!
Thank you <3

**Comment by Drahsid** [comment]
Awesome have fun
